.\" $Id: tmdns.conf.5,v 1.2 2004/02/08 23:30:59 andi Exp $
.TH TMDNS.CONF 5 "$Date: 2004/02/08 23:30:59 $" "" ""
.SH NAME
tmdns.conf \- Configuration file for tmdns
.SH SYNOPSIS
The 
.I tmdns.conf
file is the main configuration file for
.I tmdns,
a simple multicast DNS responder and mDNS to DNS bridge.
.SH FILE FORMAT
Run
.I tmdns \-P
to get a template configuration file. 
That template is documented and shows all known parameters and
default values for each parameter.
.SH "SEE ALSO"
tmdns(8),
